name: Helm Docs

on:
  pull_request:
    paths:
      - "values.yaml"
      - "README.md"
      - "Chart.yaml"
      - ".github/workflows/helm-docs.yml"

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install helm-docs
        run: |
          curl -sSL https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz -o helm-docs.tar.gz
          tar -xzf helm-docs.tar.gz
          chmod +x helm-docs
          sudo mv helm-docs /usr/local/bin/

      - name: Generate docs
        run: helm-docs

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Auto-generate README.md via helm-docs"
          file_pattern: README.md
          skip_dirty_check: false