name: Upload Helm chart to GCS bucket
on:
  push:
    tags:
      - "*"
jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    name:  Helm Chart to GCP bucket
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: "${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}"
    - name: Upload the file
      run: |
        mkdir charts
        helm dep up
        helm package . --version "${{  github.ref_name }}" --destination charts
        gcloud auth activate-service-account githubaction@keitaro-kubernetes-001.iam.gserviceaccount.com --key-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud config get-value account
        gsutil cp charts/* gs://keitaro-charts
        cd charts
        gsutil cp gs://keitaro-charts/index.yaml .
        helm repo index . --merge index.yaml
        gsutil cp index.yaml gs://keitaro-charts